// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKEhNNW8n7XttJf_s_5tseO3WXLbkbMqg',
    appId: '1:253068655608:web:004d343f3e6fb19db3740d',
    messagingSenderId: '253068655608',
    projectId: 'gen-lang-client-0158607705',
    authDomain: 'gen-lang-client-0158607705.firebaseapp.com',
    storageBucket: 'gen-lang-client-0158607705.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3sbYAb_TjUpOmCR1sxNAqjY9dCkoRPCw',
    appId: '1:253068655608:android:ee0710c20c8ee27ab3740d',
    messagingSenderId: '253068655608',
    projectId: 'gen-lang-client-0158607705',
    storageBucket: 'gen-lang-client-0158607705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhsadkixX3ouGS5Ik773pdszZ8NNC1hVw',
    appId: '1:253068655608:ios:59d2e774e0427f58b3740d',
    messagingSenderId: '253068655608',
    projectId: 'gen-lang-client-0158607705',
    storageBucket: 'gen-lang-client-0158607705.firebasestorage.app',
    iosBundleId: 'com.example.eeagle_ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhsadkixX3ouGS5Ik773pdszZ8NNC1hVw',
    appId: '1:253068655608:ios:59d2e774e0427f58b3740d',
    messagingSenderId: '253068655608',
    projectId: 'gen-lang-client-0158607705',
    storageBucket: 'gen-lang-client-0158607705.firebasestorage.app',
    iosBundleId: 'com.example.eeagle_ai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKEhNNW8n7XttJf_s_5tseO3WXLbkbMqg',
    appId: '1:253068655608:web:be3eda49d6efd0fbb3740d',
    messagingSenderId: '253068655608',
    projectId: 'gen-lang-client-0158607705',
    authDomain: 'gen-lang-client-0158607705.firebaseapp.com',
    storageBucket: 'gen-lang-client-0158607705.firebasestorage.app',
  );
}
